[package]
name = "common"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
static_assertions = "*"
chrono = "*"
regex = "*"
ahash = { version = "*", default-features = false }
indexmap = "*"
unchecked_unwrap = "*"